### ISSUE TITLE
Mark rendered partial as html safe

### ISSUE THREAD

**Issue by skamansam** [KickButtowski80/alpha-blog#1]
https://github.com/KickButtowski80/alpha-blog/blob/720144012601f92c0c9c97ec09813b0327537442/app/controllers/comments_controller.rb#L16

https://stackoverflow.com/questions/4251284/raw-vs-html-safe-vs-h-to-unescape-html

**Comment by KickButtowski80** [comment]
https://alpha-blog-kick.herokuapp.com
